version: "3"
services:
  sejuta-cita-node-app:
    ports:
      - "3000:3000"
    env_file:
      - ./.env 
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword


volumes:
  mongo-db: