version: "3"
services:
  sejuta-cita-node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env 
    command: npm run dev
    